version: "3.1"

services:
  mongo:
    ports:
      - 27017:27017
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
